c975LShop:
    roleNeeded:
        type: string
        required: true
        default: ROLE_ADMIN
        info: "User's role needed to enable access to data linked to SiteBundle: i.e. ROLE_ADMIN (default)"
    from:
        type: string
        required: true
        default: ''
        info: "Email address from which the emails are sent"
    fromName:
        type: string
        required: true
        default: ''
        info: "Name for the Email address From"
    replyTo:
        type: string
        required: true
        default: ''
        info: "Email address for replies"
    replyToName:
        type: string
        required: true
        default: ''
        info: "Name for the Email address"
    currency:
        type: string
        required: true
        default: ''
        info: "ISO on 3 letters for currency, i.e. eur"
    shipping:
        type: int
        required: true
        default: 0
        info: "Amount in cents for shipping"
    shippingFree:
        type: int
        required: true
        default: 0
        info: "Amount in cents at which shipping is offered"
    sitemapBaseUrl:
        type: string
        required: true
        default: null
        info: "Base url for sitemap creation without leading slash: i.e. https://example.com"
    stripeSecret:
        type: string
        required: true
        default: null
        info: "Your Stripe Secret Key (test|live)"
    stripeWebhookSecret:
        type: string
        required: true
        default: null
        info: "Your Stripe Webhook Secret Key (test|live)"
