services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\ShopBundle\Controller\:
        resource: '../src/Controller/*'

    c975L\ShopBundle\Form\:
        resource: '../src/Form/*'

    c975L\ShopBundle\Repository\:
        resource: '../src/Repository/*'

    c975L\ShopBundle\Service\:
        resource: '../src/Service/*'